env:
  node: true
  es6: true
extends:
  - "eslint:recommended"
  - prettier
parserOptions:
  ecmaVersion: 2018
rules:
  block-scoped-var: error
  dot-location: [error, property]
  dot-notation: error
  eqeqeq: [error, smart]
  id-match: error
  linebreak-style: [error, unix]
  no-bitwise: error
  no-console: 0
  no-debugger: error
  no-duplicate-imports: error
  no-else-return: error
  no-eval: error
  no-invalid-this: error
  no-eq-null: error
  no-fallthrough: error
  no-new-wrappers: error
  no-path-concat: error
  no-redeclare: error
  no-return-assign: error
  no-sequences: error
  no-template-curly-in-string: error
  no-trailing-spaces: error
  no-undef-init: error
  no-use-before-define: [error, nofunc]
  no-useless-escape: 0
  no-var: error
  no-void: error
  prefer-arrow-callback: error
  prefer-const: error
  radix: error
  valid-jsdoc: [error, requireReturn: false]
